### ISSUE TITLE
Doesn't appear to log out test classes?

### ISSUE THREAD

**Issue by ChrisCooney** [marschall/jdeps-maven-plugin#16]
Great plugin! I'm looking for something that'll also include my test classes, but only my production code is appearing here!

**Comment by marschall** [comment]
How did you solve the issue? Did you switch to [jdeps:test-jdkinternals](https://maven.apache.org/plugins/maven-jdeps-plugin/test-jdkinternals-mojo.html) of the official Maven plugin?
