### ISSUE TITLE
Error Invalid JAVA_HOME directory

### ISSUE THREAD

**Issue by shathor** [marschall/jdeps-maven-plugin#17]
When I try to run this plugin on Windows, it gives me an error: "Unable to find jdeps command: The environment variable JAVA_HOME=C:\Program Files\Java\jdk-11 doesn't exist or is not a valid directory."
Eventhough it exists. Otherwise it wouldn't even run.

Potential bugs in [JdepsReportMojo.java](https://github.com/marschall/jdeps-maven-plugin/blob/998595bbd8a09a46c5bf2e499fe1861ed677b245/src/main/java/com/github/marschall/jdeps/JdepsReportMojo.java):

* `Path javaHomePath = Paths.get(javaHome).resolve("bin");`
`jdepsExe = javaHomePath.resolve("bin").resolve(jdepsCommand);`
Results in jdepsExe = "C:\Program Files\Java\jdk-11\bin\bin\jdeps.exe"

* `if (!Files.exists(jdepsExe) || !Files.isDirectory(jdepsExe)) {`
It should be `Files.isDirectory(jdepsExe)` without the `!`

**Comment by shathor** [comment]
Nice, I've tried it with a simpler project and it worked now. It gave me the expected output. However a more complex project failed. I'm not sure what the problem is there and if it is related to Windows. I think the bugs I reported are fixed though. Thanks for the quick action.

Errorlog:

`[ERROR] Failed to execute goal com.github.marschall:jdeps-maven-plugin:0.5.1:jdeps (default-cli) on project ogv:
[ERROR] Exit code: 2
[ERROR] Command line was: cmd.exe /X /C ""C:\Program Files\Java\jdk-11\bin\jdeps.exe" -classpath "C:\Users\My User Name\.m2
\repository\org\apache\logging\log4j\log4j-api\2.11.1\log4j-api-2.11.1.jar;C:\Users\My User Name\.m2\repository\org\apache\
logging\log4j\log4j-core\2.11.1\log4j-core-2.11.1.jar;C:\Users\My User Name\.m2\repository\org\apache\logging\log4j\log4j-s
lf4j-impl\2.11.1\log4j-slf4j-impl-2.11.1.jar;C:\Users\My User Name\.m2\repository\com\sun\activation\javax.activation\1.2.0
\javax.activation-1.2.0.jar;C:\Users\My User Name\.m2\repository\javax\xml\bind\jaxb-api\2.3.0\jaxb-api-2.3.0.jar;C:\Users\
My User Name\.m2\repository\com\sun\xml\bind\jaxb-core\2.3.0\jaxb-core-2.3.0.jar;C:\Users\My User Name\.m2\repository\com\
sun\xml\bind\jaxb-impl\2.3.0\jaxb-impl-2.3.0.jar;C:\Users\My User Name\.m2\repository\org\openjfx\javafx-controls\11\javafx
-controls-11.jar;C:\Users\My User Name\.m2\repository\org\openjfx\javafx-fxml\11\javafx-fxml-11.jar;C:\Users\My User Name\
git\GitHub\ObjectGraphVisualization\ObjectGraphVisualization\lib\fxyzlib.jar;C:\Users\My User Name\git\GitHub\ObjectGraphVi
sualization\ObjectGraphVisualization\lib\jimObjModelImporterJFX.jar;C:\Users\My User Name\.m2\repository\org\junit\jupiter\
junit-jupiter-api\5.3.1\junit-jupiter-api-5.3.1.jar" -profile "C:\Users\My User Name\git\GitHub\ObjectGraphVisualization\Ob
jectGraphVisualization\target\classes""
`

**Comment by marschall** [comment]
Is that with this project https://github.com/Nurtak/ObjectGraphVisualization ?

**Comment by shathor** [comment]
yes
